### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by deltanedas** [azureblue/MindustryPi#1]
post it, and a script to build arm natives

**Comment by azureblue** [comment]
The JAR is in the releases section. There is no script **yet**, there were changes in the original gradle scripts and some other manual changes. The source code is mostly untouched.

**Comment by deltanedas** [comment]
Then a simple patch file would do if its not many changes

**Comment by azureblue** [comment]
Those changes are not "patch friendly". But I plan to add something. The way to go is to make it generic by adding arm target architecture (but it needs a new release of jnigen).

**Comment by deltanedas** [comment]
yeah anuke should fork jnigen for arc
