### ISSUE TITLE
failed to launch 

### ISSUE THREAD

**Issue by USMP-lancer** [azureblue/MindustryPi#3]
```Caused by: arc.util.ArcRuntimeException: java.lang.UnsatisfiedLinkError: /tmp/arc/980cf471/libarcarm64.so: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/arc/980cf471/libarcarm64.so)```
im unsure if this is from a missing file on my end or if its a missing file on your end, either way its missing

**Comment by USMP-lancer** [comment]
ok so its a version mismatch, but how the hell do i update glibc...

**Comment by USMP-lancer** [comment]
it says its the latest version, a

**Comment by USMP-lancer** [comment]
one system upgrade later and it just works

**Comment by azureblue** [comment]
Yup, it was built on the latest RPi OS and that's why it requires that glibc version. I may consider to rebuild it for earlier versions of the OS...

**Comment by USMP-lancer** [comment]
~~speaking of building how are you doing it?~~
